name: flutter_zeplin
description: Control your flutter app colors,textstyles and spaces on zeplin styleguide
version: 0.0.4
homepage: https://github.com/Abdusin/Zeplin_Flutter
repository: https://github.com/Abdusin/Zeplin_Flutter

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
